
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileTransfererImpl", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileTransfererImpl {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://service/", className = "client.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service/", className = "client.DeleteResponse")
    @Action(input = "http://service/FileTransfererImpl/deleteRequest", output = "http://service/FileTransfererImpl/deleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "upload", targetNamespace = "http://service/", className = "client.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://service/", className = "client.UploadResponse")
    @Action(input = "http://service/FileTransfererImpl/uploadRequest", output = "http://service/FileTransfererImpl/uploadResponse")
    public void upload(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://service/", className = "client.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://service/", className = "client.DownloadResponse")
    @Action(input = "http://service/FileTransfererImpl/downloadRequest", output = "http://service/FileTransfererImpl/downloadResponse")
    public byte[] download(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "showUpload", targetNamespace = "http://service/", className = "client.ShowUpload")
    @ResponseWrapper(localName = "showUploadResponse", targetNamespace = "http://service/", className = "client.ShowUploadResponse")
    @Action(input = "http://service/FileTransfererImpl/showUploadRequest", output = "http://service/FileTransfererImpl/showUploadResponse")
    public void showUpload();

}
